import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  // === PROGRESO ===
  {
    id: 'first-practice',
    name: 'Primer Paso',
    description: 'Completa tu primera práctica',
    icon: '🎯',
    category: 'progress',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-green-500',
    isSecret: false,
    progressSource: 'totalSessions',
  },
  {
    id: 'five-sessions',
    name: 'Constancia',
    description: 'Completa 5 sesiones de práctica',
    icon: '🔥',
    category: 'progress',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    color: 'bg-blue-500',
    isSecret: false,
    progressSource: 'totalSessions',
  },
  {
    id: 'ten-sessions',
    name: 'Dedicación',
    description: 'Completa 10 sesiones de práctica',
    icon: '💪',
    category: 'progress',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-indigo-500',
    isSecret: false,
    progressSource: 'totalSessions',
  },
  {
    id: 'fifty-sessions',
    name: 'Experiencia',
    description: 'Completa 50 sesiones de práctica',
    icon: '📚',
    category: 'progress',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    color: 'bg-yellow-500',
    isSecret: false,
    progressSource: 'totalSessions',
  },
  {
    id: 'hundred-sessions',
    name: 'Veterano',
    description: 'Completa 100 sesiones de práctica',
    icon: '🏆',
    category: 'progress',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-gradient-to-r from-yellow-400 to-orange-500',
    isSecret: false,
    progressSource: 'totalSessions',
  },
  {
    id: 'mini-habit',
    name: 'Mini Hábito',
    description: 'Practica 3 días seguidos por 2 semanas',
    icon: '📅',
    category: 'progress',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 14,
    color: 'bg-purple-500',
    isSecret: false,
    progressSource: 'currentStreak',
  },
  {
    id: 'commitment',
    name: 'Compromiso',
    description: '100 sesiones completadas',
    icon: '💎',
    category: 'progress',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-emerald-500',
    isSecret: false,
    progressSource: 'totalSessions',
  },
  {
    id: 'three-day-streak',
    name: 'Rutina Diaria',
    description: 'Practica 3 días consecutivos',
    icon: '📅',
    category: 'progress',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    color: 'bg-purple-500',
    isSecret: false,
    progressSource: 'currentStreak',
  },
  {
    id: 'week-streak',
    name: 'Semana de Dedicación',
    description: 'Practica 7 días consecutivos',
    icon: '📊',
    category: 'progress',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 7,
    color: 'bg-pink-500',
    isSecret: false,
    progressSource: 'currentStreak',
  },
  {
    id: 'month-streak',
    name: 'Mes de Excelencia',
    description: 'Practica 30 días consecutivos',
    icon: '📈',
    category: 'progress',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 30,
    color: 'bg-violet-500',
    isSecret: false,
    progressSource: 'currentStreak',
  },
  {
    id: 'ultimate-streak',
    name: 'Racha Legendaria',
    description: 'Practica 100 días consecutivos',
    icon: '🌟',
    category: 'progress',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-gradient-to-r from-green-400 to-emerald-500',
    isSecret: false,
    progressSource: 'currentStreak',
  },

  // === RENDIMIENTO ===
  {
    id: 'first-perfect',
    name: 'Precisión Perfecta',
    description: 'Obtén tu primer resultado exacto',
    icon: '⭐',
    category: 'performance',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-yellow-500',
    isSecret: false,
    progressSource: 'exactMatches',
  },
  {
    id: 'ten-perfect',
    name: 'Maestro de la Precisión',
    description: 'Obtén 10 resultados exactos',
    icon: '🎖️',
    category: 'performance',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-indigo-500',
    isSecret: false,
    progressSource: 'exactMatches',
  },
  {
    id: 'fifty-perfect',
    name: 'Precisión Impecable',
    description: 'Obtén 50 resultados exactos',
    icon: '💎',
    category: 'performance',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    color: 'bg-purple-500',
    isSecret: false,
    progressSource: 'exactMatches',
  },
  {
    id: 'hundred-perfect',
    name: 'Perfección Absoluta',
    description: 'Obtén 100 resultados exactos',
    icon: '👑',
    category: 'performance',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-gradient-to-r from-purple-400 to-pink-500',
    isSecret: false,
    progressSource: 'exactMatches',
  },
  {
    id: 'accuracy-master',
    name: 'Maestro de la Exactitud',
    description: 'Mantén 95% de precisión en 20 sesiones',
    icon: '🎯',
    category: 'performance',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 20,
    color: 'bg-emerald-500',
    isSecret: false,
  },
  {
    id: 'precision-hunter',
    name: 'Cazador de Precisión',
    description: '90% de precisión en 10 prácticas',
    icon: '🎯',
    category: 'performance',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-blue-500',
    isSecret: false,
  },
  {
    id: 'no-margin-error',
    name: 'Sin Margen de Error',
    description: '3 sesiones perfectas seguidas',
    icon: '✨',
    category: 'performance',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    color: 'bg-yellow-500',
    isSecret: false,
  },
  {
    id: 'speed-demon',
    name: 'Velocidad Suprema',
    description: 'Completa 10 números en menos de 30 segundos',
    icon: '🏃',
    category: 'performance',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-orange-500',
    isSecret: false,
  },
  {
    id: 'speed-legend',
    name: 'Leyenda de la Velocidad',
    description: 'Completa 20 números en menos de 1 minuto',
    icon: '🚀',
    category: 'performance',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-gradient-to-r from-blue-400 to-cyan-500',
    isSecret: false,
  },
  {
    id: 'perfect-week',
    name: 'Semana Perfecta',
    description: 'Obtén resultados exactos en 7 días consecutivos',
    icon: '💎',
    category: 'performance',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 7,
    color: 'bg-gradient-to-r from-purple-400 to-pink-500',
    isSecret: false,
  },

  // === DESAFÍOS ===
  {
    id: 'pro-mode',
    name: 'Modo Pro',
    description: 'Completa una sesión en modo Pro',
    icon: '⚡',
    category: 'challenges',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-red-500',
    isSecret: false,
  },
  {
    id: 'free-mode-master',
    name: 'Entrenamiento Infinito',
    description: 'Completa 50 números en modo libre',
    icon: '♾️',
    category: 'challenges',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    color: 'bg-teal-500',
    isSecret: false,
  },
  {
    id: 'challenge-master',
    name: 'Maestro de Desafíos',
    description: 'Completa 5 desafíos semanales',
    icon: '🏆',
    category: 'challenges',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    color: 'bg-amber-500',
    isSecret: false,
  },
  {
    id: 'expert-mode',
    name: 'Modo Experto',
    description: 'Completa 10 sesiones en modo experto',
    icon: '🧠',
    category: 'challenges',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-gradient-to-r from-indigo-400 to-purple-500',
    isSecret: true,
  },
  {
    id: 'marathon-runner',
    name: 'Maratonista',
    description: 'Practica por más de 30 minutos en una sesión',
    icon: '🏃‍♂️',
    category: 'challenges',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-green-500',
    isSecret: false,
  },
  {
    id: 'total-speed',
    name: 'Velocidad Total',
    description: 'Completa 50 números en menos de 1 minuto',
    icon: '⚡',
    category: 'challenges',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-gradient-to-r from-yellow-400 to-orange-500',
    isSecret: false,
  },
  {
    id: 'zen-marathon',
    name: 'Maratón Zen',
    description: '15 minutos en modo libre',
    icon: '🧘',
    category: 'challenges',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-emerald-500',
    isSecret: false,
  },

  // === ESTILO ===
  {
    id: 'voice-user',
    name: 'Comunicador',
    description: 'Usa la lectura por voz en 10 sesiones',
    icon: '🔊',
    category: 'style',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-blue-500',
    isSecret: false,
  },
  {
    id: 'talking-mind',
    name: 'Mente Parlante',
    description: 'Usar lectura por voz 10 veces',
    icon: '🗣️',
    category: 'style',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-indigo-500',
    isSecret: false,
  },
  {
    id: 'accessibility-champion',
    name: 'Campeón de Accesibilidad',
    description: 'Practica con alto contraste en 20 sesiones',
    icon: '♿',
    category: 'style',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 20,
    color: 'bg-orange-500',
    isSecret: false,
  },
  {
    id: 'font-explorer',
    name: 'Explorador de Fuentes',
    description: 'Prueba las 3 fuentes disponibles',
    icon: '🔤',
    category: 'style',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    color: 'bg-purple-500',
    isSecret: false,
  },
  {
    id: 'theme-collector',
    name: 'Coleccionista de Temas',
    description: 'Desbloquea 5 temas visuales diferentes',
    icon: '🎨',
    category: 'style',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    color: 'bg-gradient-to-r from-pink-400 to-rose-500',
    isSecret: false,
  },
  {
    id: 'night-owl',
    name: 'Búho Nocturno',
    description: 'Practica 50 sesiones en modo oscuro',
    icon: '🦉',
    category: 'style',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    color: 'bg-gray-700',
    isSecret: false,
  },
  {
    id: 'light-dark-mode',
    name: 'Modo Claro/Oscuro',
    description: 'Cambiar 10 veces entre temas',
    icon: '🌓',
    category: 'style',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-gray-500',
    isSecret: false,
  },
  {
    id: 'minimalist-visual',
    name: 'Minimalista Visual',
    description: 'Activar tema blanco puro',
    icon: '⚪',
    category: 'style',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-gray-300',
    isSecret: false,
  },

  // === LOGROS SECRETOS ===
  {
    id: 'early-bird',
    name: 'Madrugador',
    description: 'Practica antes de las 6 AM',
    icon: '🌅',
    category: 'progress',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-yellow-400',
    isSecret: true,
  },
  {
    id: 'night-shift',
    name: 'Turno Nocturno',
    description: 'Practica después de las 11 PM',
    icon: '🌙',
    category: 'progress',
    tier: 'bronze',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-indigo-600',
    isSecret: true,
  },
  {
    id: 'weekend-warrior',
    name: 'Guerrero de Fin de Semana',
    description: 'Practica 5 sesiones en un solo día',
    icon: '⚔️',
    category: 'progress',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-red-500',
    isSecret: true,
  },
  {
    id: 'zen-master',
    name: 'Maestro Zen',
    description: 'Practica 100 sesiones con el tema Zen',
    icon: '🧘‍♂️',
    category: 'style',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-gradient-to-r from-green-400 to-teal-500',
    isSecret: true,
  },
  {
    id: 'matrix-hacker',
    name: 'Hacker de Matrix',
    description: 'Practica 50 sesiones con el tema Matrix',
    icon: '💻',
    category: 'style',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    color: 'bg-gradient-to-r from-green-400 to-emerald-500',
    isSecret: true,
  },
  {
    id: 'retro-gamer',
    name: 'Gamer Retro',
    description: 'Practica 30 sesiones con el tema Retro',
    icon: '🎮',
    category: 'style',
    tier: 'silver',
    unlocked: false,
    progress: 0,
    maxProgress: 30,
    color: 'bg-purple-500',
    isSecret: true,
  },
  {
    id: 'perfectionist',
    name: 'Perfeccionista',
    description: 'Obtén 10 resultados exactos consecutivos',
    icon: '✨',
    category: 'performance',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-gradient-to-r from-yellow-400 to-orange-500',
    isSecret: true,
  },
  {
    id: 'speed-freak',
    name: 'Adicto a la Velocidad',
    description: 'Completa 5 sesiones rápidas consecutivas',
    icon: '⚡',
    category: 'performance',
    tier: 'gold',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    color: 'bg-yellow-500',
    isSecret: true,
  },
  {
    id: 'soroban-legend',
    name: 'Leyenda del Soroban',
    description: 'Alcanza el nivel máximo y completa todos los logros',
    icon: '👑',
    category: 'progress',
    tier: 'platinum',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-gradient-to-r from-yellow-400 via-orange-500 to-red-500',
    isSecret: true,
  },
]; 