import { Achievement } from '../types';

export const ACHIEVEMENTS: Achievement[] = [
  // Beginner Achievements
  {
    id: 'first-practice',
    name: 'Primer Paso',
    description: 'Completa tu primera práctica',
    icon: '🎯',
    category: 'beginner',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-green-500',
  },
  {
    id: 'five-sessions',
    name: 'Constancia',
    description: 'Completa 5 sesiones de práctica',
    icon: '🔥',
    category: 'beginner',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    color: 'bg-blue-500',
  },
  {
    id: 'first-perfect',
    name: 'Precisión Perfecta',
    description: 'Obtén tu primer resultado exacto',
    icon: '⭐',
    category: 'beginner',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-yellow-500',
  },
  {
    id: 'three-day-streak',
    name: 'Rutina Diaria',
    description: 'Practica 3 días consecutivos',
    icon: '📅',
    category: 'beginner',
    unlocked: false,
    progress: 0,
    maxProgress: 3,
    color: 'bg-purple-500',
  },

  // Intermediate Achievements
  {
    id: 'ten-perfect',
    name: 'Maestro de la Precisión',
    description: 'Obtén 10 resultados exactos',
    icon: '🎖️',
    category: 'intermediate',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
    color: 'bg-indigo-500',
  },
  {
    id: 'week-streak',
    name: 'Semana de Dedicación',
    description: 'Practica 7 días consecutivos',
    icon: '📊',
    category: 'intermediate',
    unlocked: false,
    progress: 0,
    maxProgress: 7,
    color: 'bg-pink-500',
  },
  {
    id: 'pro-mode',
    name: 'Modo Pro',
    description: 'Completa una sesión en modo Pro',
    icon: '⚡',
    category: 'intermediate',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-red-500',
  },
  {
    id: 'free-mode-master',
    name: 'Entrenamiento Infinito',
    description: 'Completa 50 números en modo libre',
    icon: '♾️',
    category: 'intermediate',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
    color: 'bg-teal-500',
  },

  // Advanced Achievements
  {
    id: 'speed-demon',
    name: 'Velocidad Suprema',
    description: 'Completa 10 números en menos de 30 segundos',
    icon: '🏃',
    category: 'advanced',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-orange-500',
  },
  {
    id: 'accuracy-master',
    name: 'Maestro de la Exactitud',
    description: 'Mantén 95% de precisión en 20 sesiones',
    icon: '🎯',
    category: 'advanced',
    unlocked: false,
    progress: 0,
    maxProgress: 20,
    color: 'bg-emerald-500',
  },
  {
    id: 'month-streak',
    name: 'Mes de Excelencia',
    description: 'Practica 30 días consecutivos',
    icon: '📈',
    category: 'advanced',
    unlocked: false,
    progress: 0,
    maxProgress: 30,
    color: 'bg-violet-500',
  },
  {
    id: 'challenge-master',
    name: 'Maestro de Desafíos',
    description: 'Completa 5 desafíos semanales',
    icon: '🏆',
    category: 'advanced',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
    color: 'bg-amber-500',
  },

  // Expert Achievements
  {
    id: 'soroban-master',
    name: 'Maestro del Soroban',
    description: 'Completa 100 sesiones con 90% de precisión',
    icon: '👑',
    category: 'expert',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-gradient-to-r from-yellow-400 to-orange-500',
  },
  {
    id: 'perfect-week',
    name: 'Semana Perfecta',
    description: 'Obtén resultados exactos en 7 días consecutivos',
    icon: '💎',
    category: 'expert',
    unlocked: false,
    progress: 0,
    maxProgress: 7,
    color: 'bg-gradient-to-r from-purple-400 to-pink-500',
  },
  {
    id: 'speed-legend',
    name: 'Leyenda de la Velocidad',
    description: 'Completa 20 números en menos de 1 minuto',
    icon: '🚀',
    category: 'expert',
    unlocked: false,
    progress: 0,
    maxProgress: 1,
    color: 'bg-gradient-to-r from-blue-400 to-cyan-500',
  },
  {
    id: 'ultimate-streak',
    name: 'Racha Legendaria',
    description: 'Practica 100 días consecutivos',
    icon: '🌟',
    category: 'expert',
    unlocked: false,
    progress: 0,
    maxProgress: 100,
    color: 'bg-gradient-to-r from-green-400 to-emerald-500',
  },
]; 