import { DifficultyPreset } from '../types';

export const DIFFICULTY_PRESETS: DifficultyPreset[] = [
  {
    id: 'easy',
    name: 'Fácil',
    description: 'Números pequeños, tiempo generoso',
    timeBetweenNumbers: 3,
    numberOfNumbers: 5,
    minNumber: 1,
    maxNumber: 50,
    color: 'bg-green-500',
    icon: '🌱',
  },
  {
    id: 'medium',
    name: 'Intermedio',
    description: 'Números medianos, ritmo equilibrado',
    timeBetweenNumbers: 2,
    numberOfNumbers: 10,
    minNumber: 10,
    maxNumber: 200,
    color: 'bg-blue-500',
    icon: '🌿',
  },
  {
    id: 'hard',
    name: 'Difícil',
    description: 'Números grandes, tiempo limitado',
    timeBetweenNumbers: 1.5,
    numberOfNumbers: 15,
    minNumber: 50,
    maxNumber: 500,
    color: 'bg-orange-500',
    icon: '🔥',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Máximo desafío, velocidad extrema',
    timeBetweenNumbers: 1,
    numberOfNumbers: 20,
    minNumber: 100,
    maxNumber: 999,
    color: 'bg-purple-500',
    icon: '⚡',
  },
  {
    id: 'free',
    name: 'Entrenamiento Libre',
    description: 'Números infinitos hasta que decidas parar',
    timeBetweenNumbers: 2,
    numberOfNumbers: -1, // -1 indica modo infinito
    minNumber: 1,
    maxNumber: 999,
    color: 'bg-indigo-500',
    icon: '♾️',
  },
]; 