import { DifficultyPreset } from '../types';

export const DIFFICULTY_PRESETS: DifficultyPreset[] = [
  {
    id: 'beginner',
    name: 'Principiante',
    description: 'Números pequeños, ritmo muy tranquilo',
    timeBetweenNumbers: 4,
    numberOfNumbers: 3,
    minNumber: 1,
    maxNumber: 20,
    color: 'bg-lime-500',
    icon: '🌱',
  },
  {
    id: 'beginner-plus',
    name: 'Principiante Plus',
    description: 'Un poco más de reto que Principiante, pero aún amigable',
    timeBetweenNumbers: 2,
    numberOfNumbers: 3,
    minNumber: 1,
    maxNumber: 30,
    color: 'bg-lime-400',
    icon: '��',
  },
  {
    id: 'easy',
    name: 'Fácil',
    description: 'Perfecto para empezar a practicar',
    timeBetweenNumbers: 3,
    numberOfNumbers: 5,
    minNumber: 1,
    maxNumber: 50,
    color: 'bg-green-500',
    icon: '🍃',
  },
  {
    id: 'medium',
    name: 'Intermedio',
    description: 'Para practicantes regulares',
    timeBetweenNumbers: 2,
    numberOfNumbers: 10,
    minNumber: 1,
    maxNumber: 100,
    color: 'bg-blue-500',
    icon: '⚡',
  },
  {
    id: 'hard',
    name: 'Difícil',
    description: 'Para usuarios avanzados',
    timeBetweenNumbers: 1.5,
    numberOfNumbers: 15,
    minNumber: 1,
    maxNumber: 200,
    color: 'bg-orange-500',
    icon: '🔥',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'El máximo desafío',
    timeBetweenNumbers: 1,
    numberOfNumbers: 20,
    minNumber: 1,
    maxNumber: 500,
    color: 'bg-purple-500',
    icon: '👑',
  },
  {
    id: 'free',
    name: 'Entrenamiento Libre',
    description: 'Practica sin límites de tiempo',
    timeBetweenNumbers: 2,
    numberOfNumbers: 999,
    minNumber: 1,
    maxNumber: 100,
    color: 'bg-indigo-500',
    icon: '♾️',
  },
  {
    id: 'tutorial',
    name: 'Tutorial',
    description: 'Aprende a usar el Soroban paso a paso',
    timeBetweenNumbers: 3,
    numberOfNumbers: 3,
    minNumber: 1,
    maxNumber: 9,
    color: 'bg-cyan-500',
    icon: '🎓',
  },
  {
    id: 'beginner-fast',
    name: 'Principiante Fast',
    description: 'Números pequeños, ritmo rápido y varios números',
    timeBetweenNumbers: 1,
    numberOfNumbers: 8,
    minNumber: 1,
    maxNumber: 9,
    color: 'bg-yellow-400',
    icon: '⚡🌱',
  },
  {
    id: 'duo-fast',
    name: 'Dúo Rápido',
    description: 'Solo dos números pequeños, ritmo ultra rápido',
    timeBetweenNumbers: 0.8,
    numberOfNumbers: 2,
    minNumber: 1,
    maxNumber: 9,
    color: 'bg-pink-400',
    icon: '⚡2️⃣',
  },
]; 